### ISSUE TITLE
Parse error when having '/" in commit title probably.

### ISSUE THREAD

**Issue by pmodin** [BonnierGaming/deploy-request-generator#2]
```
$ ~/Code/deploy-request-generator/deployrequest
Does the deployer need any special instructions? [y/N] y
Is 'master' the target branch? [Y/n]
The file /{WITHELD-PROJECTDIR}/Merge remote-tracking branch 'origin/{WITHELD-BRANCH}' into deploy-2015-08-04.1
010e8b4 Update migration file

# Shortstat
8 files changed, 416 insertions(+), 18 deletions(-)

# Referenced issues
https:/project.{WITHELD-issuetracker}.com/issues/8358
https:/project.{WITHELD-issuetracker}.com/issues/17270
 does not exist.
```

There are two commits in the branch, 
1. Revert "Revert "Merge remote-tracking branch 'origin/{WITHELD-BRANCH}' into deploy-2015-08-04.1""
2. Update migration file

I expect the 1st commit, that includes both ' and " in commit title, to be the issue.

**Comment by linduxed** [comment]
My guess would be that it breaks [when the OS-specific command tries to open the generated `mailto` link](https://github.com/BonnierGaming/deploy-request-generator/blob/master/cli.rb#L83).

Off the top of my head, I can't figure out where the quote escaping is to be done. Maybe something like [these lines](https://github.com/bonniergaming/deploy-request-generator/blob/master/email_formatter.rb#L37-L39) will once more be necessary?

I'll look into this some time later this week.

**Comment by jsageryd** [comment]
In the hack I did before I just made those errors go away by replacing those chars with `_`. Apparently I missed `/`. Scroll to the end of the line (yes, I just said that) of https://github.com/jsageryd/.config.d/blob/evoke/scripts/deploy/deployrequest.bash#L34

**Comment by pmodin** [comment]
ah, there's a / in there as well. Hmm that might be it. @linduxed can you reproduce on linux?

**Comment by linduxed** [comment]
No, if I go to the branch where this happened I don't get the error.

**Comment by linduxed** [comment]
Could you check whether f842fdfb225e07764c7c3612966f50a409864878 fixes this problem?

**Comment by pmodin** [comment]
@linduxed it does, thanks :smiley_cat:
