### ISSUE TITLE
Mail content gets cut off at first & character of the content

### ISSUE THREAD

**Issue by alexteg** [BonnierGaming/deploy-request-generator#4]
When creating a deploy request for a branch that contains commits that contain the `&` character in the subject the output from deploy requester gets cut off at the first `&` character in the email. I'm unsure at what level it happens or if it is Mac OS or Thunderbird specific, but my guess is that the `&` is somehow interpreted as an operator.

I am using Mac OS X 10.10.5, iTerm 2.1.1, zsh 5.0.7 and Thunderbird 38.2.0 with the deploy-request-generator at revision deaf701.

This could possibly be related to #2.

**Comment by linduxed** [comment]
This should be fixed as of f842fdfb225e07764c7c3612966f50a409864878.
